<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="42958" started-at="2019-11-19T18:57:47Z" finished-at="2019-11-19T18:58:30Z">
    <groups>
    </groups>
    <test name="Validating  title" duration-ms="25534" started-at="2019-11-19T18:57:47Z" finished-at="2019-11-19T18:58:12Z">
      <class name="TestCases.LoginTest">
        <test-method status="PASS" signature="InvokeBrowser()[pri:0, instance:TestCases.LoginTest@617c74e5]" name="InvokeBrowser" is-config="true" duration-ms="8834" started-at="2019-11-19T18:57:47Z" finished-at="2019-11-19T18:57:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvokeBrowser -->
        <test-method status="PASS" signature="Loginverify()[pri:0, instance:TestCases.LoginTest@617c74e5]" name="Loginverify" duration-ms="16396" started-at="2019-11-19T18:57:56Z" finished-at="2019-11-19T18:58:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Loginverify -->
        <test-method status="PASS" signature="logout()[pri:0, instance:TestCases.LoginTest@617c74e5]" name="logout" is-config="true" duration-ms="85" started-at="2019-11-19T18:58:12Z" finished-at="2019-11-19T18:58:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- TestCases.LoginTest -->
    </test> <!-- Validating  title -->
    <test name="Vidisible text" duration-ms="8949" started-at="2019-11-19T18:58:13Z" finished-at="2019-11-19T18:58:21Z">
      <class name="TestCases.Visibletext">
        <test-method status="PASS" signature="InvokeBrowser()[pri:0, instance:TestCases.Visibletext@50b472aa]" name="InvokeBrowser" is-config="true" duration-ms="8703" started-at="2019-11-19T18:58:13Z" finished-at="2019-11-19T18:58:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvokeBrowser -->
        <test-method status="PASS" signature="Loginverify()[pri:0, instance:TestCases.Visibletext@50b472aa]" name="Loginverify" duration-ms="113" started-at="2019-11-19T18:58:21Z" finished-at="2019-11-19T18:58:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Loginverify -->
        <test-method status="PASS" signature="logout()[pri:0, instance:TestCases.Visibletext@50b472aa]" name="logout" is-config="true" duration-ms="132" started-at="2019-11-19T18:58:21Z" finished-at="2019-11-19T18:58:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- TestCases.Visibletext -->
    </test> <!-- Vidisible text -->
    <test name="login test" duration-ms="8061" started-at="2019-11-19T18:58:22Z" finished-at="2019-11-19T18:58:30Z">
      <class name="TestCases.Vlaidation">
        <test-method status="PASS" signature="InvokeBrowser()[pri:0, instance:TestCases.Vlaidation@15c43bd9]" name="InvokeBrowser" is-config="true" duration-ms="6586" started-at="2019-11-19T18:58:22Z" finished-at="2019-11-19T18:58:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvokeBrowser -->
        <test-method status="FAIL" signature="Loginverify1()[pri:0, instance:TestCases.Vlaidation@15c43bd9]" name="Loginverify1" duration-ms="48" started-at="2019-11-19T18:58:28Z" finished-at="2019-11-19T18:58:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [FEATURED COURSE] but found [FEATURED COURSES]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [FEATURED COURSE] but found [FEATURED COURSES]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at TestCases.Vlaidation.Loginverify1(Vlaidation.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Loginverify1 -->
        <test-method status="PASS" signature="logout()[pri:0, instance:TestCases.Vlaidation@15c43bd9]" name="logout" is-config="true" duration-ms="773" started-at="2019-11-19T18:58:29Z" finished-at="2019-11-19T18:58:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- TestCases.Vlaidation -->
    </test> <!-- login test -->
  </suite> <!-- Suite -->
</testng-results>
